-- WWTBAM question seed — hand-written starter set
-- 240 questions: 8 categories x 15 difficulty tiers x 2 questions
--
-- Safe to re-run: clears existing questions first.
-- For a larger, more varied set run: npx tsx scripts/generate-questions.ts

DELETE FROM questions;

INSERT INTO questions (text, options, correct_idx, category, difficulty) VALUES

-- ═══════════════════ GENERAL KNOWLEDGE ═══════════════════
('How many days are there in a week?', ARRAY['Seven','Eight','Five','Six'], 0, 'random', 1),
('What colour do you get when you mix red and white?', ARRAY['Purple','Pink','Orange','Grey'], 1, 'random', 1),
('How many continents are there on Earth?', ARRAY['Five','Six','Seven','Eight'], 2, 'random', 2),
('Which is the largest mammal on Earth?', ARRAY['Giraffe','Hippopotamus','African elephant','Blue whale'], 3, 'random', 2),
('What is the capital city of Japan?', ARRAY['Tokyo','Bangkok','Seoul','Beijing'], 0, 'random', 3),
('How many sides does a hexagon have?', ARRAY['Five','Six','Seven','Eight'], 1, 'random', 3),
('Which planet is known as the Red Planet?', ARRAY['Mercury','Venus','Mars','Jupiter'], 2, 'random', 4),
('What is the chemical symbol for gold?', ARRAY['Ag','Go','Gd','Au'], 3, 'random', 4),
('Who painted the Mona Lisa?', ARRAY['Leonardo da Vinci','Raphael','Caravaggio','Michelangelo'], 0, 'random', 5),
('Which is the largest ocean on Earth?', ARRAY['Indian','Pacific','Arctic','Atlantic'], 1, 'random', 5),
('In which year did the Berlin Wall fall?', ARRAY['1993','1987','1989','1991'], 2, 'random', 6),
('What is the smallest prime number?', ARRAY['Three','Zero','One','Two'], 3, 'random', 6),
('Which country gifted the Statue of Liberty to the United States?', ARRAY['France','Spain','Italy','Britain'], 0, 'random', 7),
('How many bones are there in the adult human body?', ARRAY['186','206','226','246'], 1, 'random', 7),
('Who wrote the novel 1984?', ARRAY['William Golding','Aldous Huxley','George Orwell','Ray Bradbury'], 2, 'random', 8),
('What is the hardest naturally occurring substance?', ARRAY['Titanium','Quartz','Steel','Diamond'], 3, 'random', 8),
('Which element has the atomic number 1?', ARRAY['Hydrogen','Oxygen','Carbon','Helium'], 0, 'random', 9),
('In Greek mythology, who is the god of the sea?', ARRAY['Hades','Poseidon','Apollo','Zeus'], 1, 'random', 9),
('In which year did the Second World War end?', ARRAY['1943','1944','1945','1946'], 2, 'random', 10),
('What is the currency of Switzerland?', ARRAY['Krona','Mark','Euro','Swiss franc'], 3, 'random', 10),
('Who discovered penicillin?', ARRAY['Alexander Fleming','Robert Koch','Joseph Lister','Louis Pasteur'], 0, 'random', 11),
('How many keys does a standard piano have?', ARRAY['80','88','96','76'], 1, 'random', 11),
('What is the capital of Australia?', ARRAY['Sydney','Melbourne','Canberra','Perth'], 2, 'random', 12),
('The study of fungi is known as what?', ARRAY['Botany','Zoology','Entomology','Mycology'], 3, 'random', 12),
('Who was the first woman to win a Nobel Prize?', ARRAY['Marie Curie','Lise Meitner','Rosalind Franklin','Dorothy Hodgkin'], 0, 'random', 13),
('What is the longest bone in the human body?', ARRAY['Tibia','Femur','Humerus','Fibula'], 1, 'random', 13),
('In which year was the Magna Carta sealed?', ARRAY['1415','1066','1215','1315'], 2, 'random', 14),
('Which country officially spans the most time zones?', ARRAY['China','Russia','United States','France'], 3, 'random', 14),
('What is the smallest country in the world by area?', ARRAY['Vatican City','San Marino','Monaco','Nauru'], 0, 'random', 15),
('Which mathematician proved Fermat''s Last Theorem?', ARRAY['John Nash','Andrew Wiles','Grigori Perelman','Paul Erdos'], 1, 'random', 15),

-- ═══════════════════ MEDICINE ═══════════════════
('Which organ pumps blood around the body?', ARRAY['Kidney','Liver','Heart','Lung'], 2, 'medicine', 1),
('How many lungs does a healthy human have?', ARRAY['Three','Four','One','Two'], 3, 'medicine', 1),
('What does a thermometer measure?', ARRAY['Temperature','Pulse rate','Body weight','Blood pressure'], 0, 'medicine', 2),
('Which vitamin does the body produce from sunlight?', ARRAY['Vitamin C','Vitamin D','Vitamin K','Vitamin A'], 1, 'medicine', 2),
('What is the largest organ of the human body?', ARRAY['Heart','Liver','Skin','Brain'], 2, 'medicine', 3),
('What is normal human body temperature in Celsius?', ARRAY['39 degrees','41 degrees','35 degrees','37 degrees'], 3, 'medicine', 3),
('Which blood cells primarily fight infection?', ARRAY['White cells','Platelets','Plasma cells','Red cells'], 0, 'medicine', 4),
('Insulin is used to treat which condition?', ARRAY['Asthma','Diabetes','Anaemia','Arthritis'], 1, 'medicine', 4),
('Which organ produces bile?', ARRAY['Spleen','Pancreas','Liver','Stomach'], 2, 'medicine', 5),
('How many chambers does the human heart have?', ARRAY['Five','Two','Three','Four'], 3, 'medicine', 5),
('The medical study of the heart is called what?', ARRAY['Cardiology','Oncology','Urology','Neurology'], 0, 'medicine', 6),
('Which gland produces insulin?', ARRAY['Thyroid','Pancreas','Adrenal','Pituitary'], 1, 'medicine', 6),
('What is the medical term for high blood pressure?', ARRAY['Bradycardia','Hypotension','Hypertension','Tachycardia'], 2, 'medicine', 7),
('Deficiency of which vitamin causes scurvy?', ARRAY['Vitamin D','Vitamin A','Vitamin B12','Vitamin C'], 3, 'medicine', 7),
('What is the largest artery in the human body?', ARRAY['Aorta','Carotid artery','Femoral artery','Pulmonary artery'], 0, 'medicine', 8),
('Which bone protects the brain?', ARRAY['Sternum','Cranium','Pelvis','Scapula'], 1, 'medicine', 8),
('What does MRI stand for?', ARRAY['Molecular Resonance Index','Magnetic Radiology Interface','Magnetic Resonance Imaging','Medical Radiation Imaging'], 2, 'medicine', 9),
('What is a normal resting heart rate for an adult?', ARRAY['100 to 140 bpm','140 to 180 bpm','40 to 60 bpm','60 to 100 bpm'], 3, 'medicine', 9),
('Which hormone chiefly regulates metabolic rate?', ARRAY['Thyroxine','Cortisol','Adrenaline','Insulin'], 0, 'medicine', 10),
('Which part of the brain controls balance and coordination?', ARRAY['Cerebrum','Cerebellum','Medulla','Thalamus'], 1, 'medicine', 10),
('What is the medical term for inflammation of the kidney?', ARRAY['Gastritis','Cystitis','Nephritis','Hepatitis'], 2, 'medicine', 11),
('What is the approximate normal pH of human blood?', ARRAY['8.4','5.4','6.4','7.4'], 3, 'medicine', 11),
('Which nerve supplies the diaphragm?', ARRAY['Phrenic nerve','Sciatic nerve','Median nerve','Vagus nerve'], 0, 'medicine', 12),
('To which drug class does ibuprofen belong?', ARRAY['Opioid','NSAID','Corticosteroid','Antibiotic'], 1, 'medicine', 12),
('What does the Glasgow Coma Scale assess?', ARRAY['Visual acuity','Pain severity','Level of consciousness','Reflex response'], 2, 'medicine', 13),
('Which cranial nerve has the longest course in the body?', ARRAY['Optic','Trigeminal','Facial','Vagus'], 3, 'medicine', 13),
('Cushing syndrome results from an excess of which hormone?', ARRAY['Cortisol','Insulin','Calcitonin','Aldosterone'], 0, 'medicine', 14),
('Which coronary artery is most often implicated in major heart attacks?', ARRAY['Right coronary','Left anterior descending','Circumflex','Posterior descending'], 1, 'medicine', 14),
('Deficiency of which enzyme causes Tay-Sachs disease?', ARRAY['Sphingomyelinase','Alpha-galactosidase','Hexosaminidase A','Glucocerebrosidase'], 2, 'medicine', 15),
('Which immunoglobulin class is most abundant in human serum?', ARRAY['IgM','IgE','IgA','IgG'], 3, 'medicine', 15),

-- ═══════════════════ LAW ═══════════════════
('What is the name of the person who decides a verdict in a jury trial?', ARRAY['Juror','Clerk','Usher','Bailiff'], 0, 'law', 1),
('What do you call the written rules made by a government?', ARRAY['Lists','Laws','Notes','Orders'], 1, 'law', 1),
('Who presides over a courtroom?', ARRAY['Clerk','Lawyer','Judge','Witness'], 2, 'law', 2),
('What is a person accused of a crime called?', ARRAY['Witness','Juror','Plaintiff','Defendant'], 3, 'law', 2),
('What does the phrase "innocent until proven guilty" describe?', ARRAY['Burden of proof','Right to silence','Double jeopardy','Habeas corpus'], 0, 'law', 3),
('A formal decision by a jury is known as what?', ARRAY['Motion','Verdict','Appeal','Writ'], 1, 'law', 3),
('What is the term for a written court order requiring attendance?', ARRAY['Warrant','Injunction','Subpoena','Affidavit'], 2, 'law', 4),
('Which branch of law deals with disputes between private parties?', ARRAY['Military law','Canon law','Criminal law','Civil law'], 3, 'law', 4),
('What is a sworn written statement used as evidence called?', ARRAY['Affidavit','Subpoena','Deposition','Indictment'], 0, 'law', 5),
('What is the highest court in the United States?', ARRAY['Federal Court','Supreme Court','High Court','Court of Appeal'], 1, 'law', 5),
('What does a court injunction do?', ARRAY['Selects a jury','Awards damages','Orders a party to act or stop acting','Dismisses a case'], 2, 'law', 6),
('What is the legal term for killing without premeditation?', ARRAY['Assault','Battery','Murder','Manslaughter'], 3, 'law', 6),
('What is the principle preventing trial twice for the same offence?', ARRAY['Double jeopardy','Habeas corpus','Res judicata','Estoppel'], 0, 'law', 7),
('In a civil case, who bears the burden of proof?', ARRAY['Defendant','Plaintiff','Judge','Jury'], 1, 'law', 7),
('What does "habeas corpus" protect against?', ARRAY['Illegal search','Forced testimony','Unlawful detention','Unfair taxation'], 2, 'law', 8),
('What is the standard of proof in most criminal trials?', ARRAY['Clear and convincing','Probable cause','Balance of probabilities','Beyond reasonable doubt'], 3, 'law', 8),
('What is a legally binding agreement between parties called?', ARRAY['Contract','Tort','Statute','Decree'], 0, 'law', 9),
('Which area of law covers civil wrongs causing harm?', ARRAY['Trust law','Tort law','Contract law','Property law'], 1, 'law', 9),
('What does "mens rea" refer to?', ARRAY['Reasonable doubt','Guilty act','Guilty mind','Legal duty'], 2, 'law', 10),
('What is the term for a lower court decision being overturned?', ARRAY['Affirmed','Vacated','Remanded','Reversed'], 3, 'law', 10),
('What does "stare decisis" mean?', ARRAY['Let the decision stand','The state decides','Standing to sue','Silence implies consent'], 0, 'law', 11),
('What is "actus reus"?', ARRAY['The court record','The guilty act','The guilty mind','The legal remedy'], 1, 'law', 11),
('Which document limited the power of the English monarch in 1215?', ARRAY['Act of Settlement','Bill of Rights','Magna Carta','Petition of Right'], 2, 'law', 12),
('What is the legal term for a person who makes a will?', ARRAY['Trustee','Executor','Beneficiary','Testator'], 3, 'law', 12),
('What does the doctrine of "res ipsa loquitur" allow a court to infer?', ARRAY['Negligence','Intent','Consent','Damages'], 0, 'law', 13),
('In contract law, what is "consideration"?', ARRAY['A judicial review','Something of value exchanged','A period of reflection','A written clause'], 1, 'law', 13),
('What is an "ultra vires" act?', ARRAY['Made under duress','Void for vagueness','Beyond legal authority','Against public policy'], 2, 'law', 14),
('Which principle holds that ignorance of the law is no defence?', ARRAY['Nemo dat quod non habet','Volenti non fit injuria','Caveat emptor','Ignorantia juris non excusat'], 3, 'law', 14),
('What does the "fruit of the poisonous tree" doctrine exclude?', ARRAY['Evidence derived from an illegal search','Hearsay testimony','Expert opinion','Character evidence'], 0, 'law', 15),
('What is "estoppel by laches" based on?', ARRAY['An implied contract','Unreasonable delay in asserting a right','A prior written promise','A mistake of fact'], 1, 'law', 15),

-- ═══════════════════ ENGINEERING & SOFTWARE ═══════════════════
('What does the abbreviation PC stand for?', ARRAY['Program Code','Primary Chip','Personal Computer','Public Console'], 2, 'engineering', 1),
('Which device is used to type text into a computer?', ARRAY['Printer','Speaker','Monitor','Keyboard'], 3, 'engineering', 1),
('What does WWW stand for?', ARRAY['World Wide Web','Wired Web Work','Web Wide World','World Web Wire'], 0, 'engineering', 2),
('Which company created the Windows operating system?', ARRAY['Apple','Microsoft','Google','IBM'], 1, 'engineering', 2),
('What does CPU stand for?', ARRAY['Central Program Utility','Core Processing Unifier','Central Processing Unit','Computer Power Unit'], 2, 'engineering', 3),
('How many bits are there in a byte?', ARRAY['Ten','Four','Six','Eight'], 3, 'engineering', 3),
('Which language is primarily used to style web pages?', ARRAY['CSS','SQL','JSON','HTML'], 0, 'engineering', 4),
('What does RAM stand for?', ARRAY['Read Access Memory','Random Access Memory','Rapid Array Module','Runtime Allocation Map'], 1, 'engineering', 4),
('In binary, what is the decimal number 2?', ARRAY['20','01','10','11'], 2, 'engineering', 5),
('Which symbol commonly begins a comment in Python?', ARRAY['--','/*','//','#'], 3, 'engineering', 5),
('What does HTTP stand for?', ARRAY['HyperText Transfer Protocol','High Transfer Text Protocol','HyperText Transmission Program','Host Transfer Protocol'], 0, 'engineering', 6),
('Which data structure operates on a last-in, first-out basis?', ARRAY['Queue','Stack','Array','Tree'], 1, 'engineering', 6),
('What does SQL stand for?', ARRAY['System Quality Language','Standard Query Layer','Structured Query Language','Sequential Query Logic'], 2, 'engineering', 7),
('Which port does HTTPS use by default?', ARRAY['8080','22','80','443'], 3, 'engineering', 7),
('What is the time complexity of binary search on a sorted array?', ARRAY['O(log n)','O(n log n)','O(1)','O(n)'], 0, 'engineering', 8),
('Which protocol resolves domain names to IP addresses?', ARRAY['SMTP','DNS','DHCP','FTP'], 1, 'engineering', 8),
('In object-oriented programming, what does inheritance allow?', ARRAY['A method to run twice','Memory to be shared','A class to derive from another','Two classes to merge'], 2, 'engineering', 9),
('What does API stand for?', ARRAY['Automated Process Integration','Applied Program Instruction','Advanced Protocol Interface','Application Programming Interface'], 3, 'engineering', 9),
('Which sorting algorithm has the best average time complexity?', ARRAY['Quicksort','Insertion sort','Selection sort','Bubble sort'], 0, 'engineering', 10),
('What is a race condition?', ARRAY['A failed network call','Behaviour depending on uncontrolled timing','A loop running too fast','A memory overflow'], 1, 'engineering', 10),
('What does ACID stand for in database systems?', ARRAY['Array, Cache, Index, Data','Atomic, Cached, Indexed, Durable','Atomicity, Consistency, Isolation, Durability','Access, Control, Integrity, Design'], 2, 'engineering', 11),
('Which HTTP status code indicates a resource was not found?', ARRAY['500','301','403','404'], 3, 'engineering', 11),
('In Big O notation, what is the complexity of a nested loop over n items?', ARRAY['O(n squared)','O(log n)','O(2 to the n)','O(n)'], 0, 'engineering', 12),
('What is the purpose of a mutex?', ARRAY['Cache results','Prevent concurrent access to a resource','Compress data','Encrypt traffic'], 1, 'engineering', 12),
('Which consensus algorithm is used by Raft to elect a leader?', ARRAY['Round robin','Priority queue','Randomised election timeouts','Proof of work'], 2, 'engineering', 13),
('What does the CAP theorem state you must trade off?', ARRAY['Cost, Accuracy, Performance','Cache, API, Protocol','Concurrency, Atomicity, Persistence','Consistency, Availability, Partition tolerance'], 3, 'engineering', 13),
('In cryptography, what does a hash function guarantee?', ARRAY['Deterministic fixed-length output','Reversible encryption','Compressed storage','Unique input recovery'], 0, 'engineering', 14),
('What is tail call optimisation?', ARRAY['Deferring garbage collection','Reusing a stack frame for a final call','Caching the last function result','Inlining short functions'], 1, 'engineering', 14),
('What problem does the Byzantine Generals Problem describe?', ARRAY['Balancing network load','Compressing large files','Reaching consensus with unreliable actors','Sorting distributed data'], 2, 'engineering', 15),
('In type theory, what does the Curry-Howard correspondence relate?', ARRAY['Types and memory layout','Functions and databases','Compilers and interpreters','Programs and mathematical proofs'], 3, 'engineering', 15),

-- ═══════════════════ FINANCE & BUSINESS ═══════════════════
('What do you call money kept in a bank?', ARRAY['Savings','Wages','Taxes','Bills'], 0, 'finance', 1),
('What is the currency of the United States?', ARRAY['Pound','Dollar','Euro','Yen'], 1, 'finance', 1),
('What does it mean to "buy" something?', ARRAY['Borrow it','Repair it','Exchange money for goods','Give it away'], 2, 'finance', 2),
('What is a person who buys goods called?', ARRAY['Supplier','Auditor','Seller','Customer'], 3, 'finance', 2),
('What is the currency of the United Kingdom?', ARRAY['Pound sterling','Franc','Krona','Euro'], 0, 'finance', 3),
('What does a profit mean for a business?', ARRAY['Debts increased','Income exceeds costs','Costs exceed income','No sales made'], 1, 'finance', 3),
('What is interest on a loan?', ARRAY['A refund','A discount','The cost of borrowing','A type of tax'], 2, 'finance', 4),
('What does the abbreviation CEO stand for?', ARRAY['Central Executive Operator','Chief Economic Officer','Corporate Equity Owner','Chief Executive Officer'], 3, 'finance', 4),
('What is inflation?', ARRAY['A general rise in prices','A fall in employment','A rise in exports','A drop in interest rates'], 0, 'finance', 5),
('What does a share represent?', ARRAY['A tax credit','Ownership in a company','A loan to a company','A company debt'], 1, 'finance', 5),
('What does GDP stand for?', ARRAY['Global Domestic Price','Gross Debt Position','Gross Domestic Product','General Development Plan'], 2, 'finance', 6),
('What is a budget deficit?', ARRAY['Revenue exceeds spending','Zero net spending','Rising exports','Spending exceeds revenue'], 3, 'finance', 6),
('In accounting, what does the balance sheet equation state?', ARRAY['Assets equal liabilities plus equity','Revenue minus costs equals profit','Cash equals debt','Income equals expenditure'], 0, 'finance', 7),
('What is a bull market?', ARRAY['Volatility is zero','Prices are rising','Prices are falling','Trading is halted'], 1, 'finance', 7),
('What does ROI stand for?', ARRAY['Revenue over Income','Risk of Insolvency','Return on Investment','Rate of Inflation'], 2, 'finance', 8),
('What is a dividend?', ARRAY['A loan repayment','A tax on shares','A brokerage fee','A share of profits paid to shareholders'], 3, 'finance', 8),
('What does liquidity measure?', ARRAY['How quickly an asset converts to cash','Total company debt','Annual profit margin','Market share'], 0, 'finance', 9),
('What is the primary role of a central bank?', ARRAY['Setting tax rates','Managing monetary policy','Selling shares','Auditing companies'], 1, 'finance', 9),
('What does diversification aim to reduce?', ARRAY['Liquidity','Taxes','Risk','Return'], 2, 'finance', 10),
('What is an IPO?', ARRAY['A merger of two firms','A government bond','An internal profit order','A company first selling shares publicly'], 3, 'finance', 10),
('What does a bond coupon rate represent?', ARRAY['The annual interest paid','The purchase price','The maturity date','The credit rating'], 0, 'finance', 11),
('What is the price-to-earnings ratio used to assess?', ARRAY['Market volatility','Company valuation','Debt levels','Cash flow'], 1, 'finance', 11),
('In economics, what does elasticity of demand measure?', ARRAY['Rate of inflation','Supply capacity','Sensitivity of demand to price','Total market size'], 2, 'finance', 12),
('What is quantitative easing?', ARRAY['Raising income tax','Cutting public spending','Devaluing a currency by decree','A central bank buying assets to add money to the economy'], 3, 'finance', 12),
('What does the term "hedging" mean in finance?', ARRAY['Offsetting potential losses','Maximising leverage','Avoiding taxation','Delaying settlement'], 0, 'finance', 13),
('What does EBITDA exclude?', ARRAY['Assets and liabilities','Interest, taxes, depreciation and amortisation','Revenue and costs','Equity and debt'], 1, 'finance', 13),
('What does the efficient market hypothesis assert?', ARRAY['Arbitrage is impossible','Volatility is constant','Prices reflect all available information','Markets always rise over time'], 2, 'finance', 14),
('In the Black-Scholes model, what does "volatility" represent?', ARRAY['The risk-free rate','The strike price','The time to expiry','The standard deviation of returns'], 3, 'finance', 14),
('What is the Modigliani-Miller theorem concerned with?', ARRAY['Capital structure irrelevance','Optimal taxation','Consumer choice','Wage determination'], 0, 'finance', 15),
('What does a negative yield curve inversion typically signal?', ARRAY['Rising employment','A potential recession','Immediate inflation','Currency appreciation'], 1, 'finance', 15),

-- ═══════════════════ SCIENCE ═══════════════════
('What do bees collect from flowers?', ARRAY['Sand','Leaves','Nectar','Water'], 2, 'science', 1),
('How many legs does a spider have?', ARRAY['Ten','Twelve','Six','Eight'], 3, 'science', 1),
('What gas do humans need to breathe to survive?', ARRAY['Oxygen','Helium','Hydrogen','Nitrogen'], 0, 'science', 2),
('What is frozen water called?', ARRAY['Steam','Ice','Mist','Foam'], 1, 'science', 2),
('Which planet do we live on?', ARRAY['Mars','Venus','Earth','Saturn'], 2, 'science', 3),
('What force pulls objects toward the ground?', ARRAY['Friction','Tension','Magnetism','Gravity'], 3, 'science', 3),
('What is the chemical formula for water?', ARRAY['H2O','O2','NaCl','CO2'], 0, 'science', 4),
('How many planets are in our solar system?', ARRAY['Seven','Eight','Nine','Ten'], 1, 'science', 4),
('What process do plants use to make food from sunlight?', ARRAY['Fermentation','Respiration','Photosynthesis','Digestion'], 2, 'science', 5),
('What is the centre of an atom called?', ARRAY['Proton','Shell','Electron','Nucleus'], 3, 'science', 5),
('At what temperature does water boil at sea level in Celsius?', ARRAY['100','110','120','90'], 0, 'science', 6),
('Which gas makes up most of the Earth''s atmosphere?', ARRAY['Oxygen','Nitrogen','Carbon dioxide','Argon'], 1, 'science', 6),
('What is the speed of light in a vacuum, approximately?', ARRAY['30,000 km per second','3,000 km per second','300,000 km per second','300,000 km per hour'], 2, 'science', 7),
('Which particle carries a negative charge?', ARRAY['Neutron','Photon','Proton','Electron'], 3, 'science', 7),
('What is the most abundant element in the universe?', ARRAY['Hydrogen','Oxygen','Carbon','Helium'], 0, 'science', 8),
('Who developed the theory of general relativity?', ARRAY['Isaac Newton','Albert Einstein','Niels Bohr','Max Planck'], 1, 'science', 8),
('What is the powerhouse of the cell?', ARRAY['Golgi body','Nucleus','Mitochondrion','Ribosome'], 2, 'science', 9),
('Which law states that energy cannot be created or destroyed?', ARRAY['Newton''s second law','Ohm''s law','Boyle''s law','Conservation of energy'], 3, 'science', 9),
('What is the pH value of a neutral solution?', ARRAY['Seven','Nine','Eleven','Five'], 0, 'science', 10),
('How many chromosomes does a typical human cell contain?', ARRAY['23','46','48','92'], 1, 'science', 10),
('What subatomic particles make up a proton?', ARRAY['Bosons','Neutrinos','Quarks','Leptons'], 2, 'science', 11),
('Which scientist proposed the periodic table of elements?', ARRAY['Antoine Lavoisier','John Dalton','Robert Boyle','Dmitri Mendeleev'], 3, 'science', 11),
('What does the second law of thermodynamics describe?', ARRAY['Entropy always increases in an isolated system','Energy is conserved','Force equals mass times acceleration','Pressure varies with volume'], 0, 'science', 12),
('What is the half-life of carbon-14, approximately?', ARRAY['1,600 years','5,730 years','12,000 years','50,000 years'], 1, 'science', 12),
('What is the Heisenberg uncertainty principle about?', ARRAY['Energy quantisation','Wave interference','Limits on knowing position and momentum together','The speed of light being constant'], 2, 'science', 13),
('Which organelle is responsible for protein synthesis?', ARRAY['Lysosome','Vacuole','Centriole','Ribosome'], 3, 'science', 13),
('What is the Chandrasekhar limit related to?', ARRAY['Maximum mass of a stable white dwarf','Speed of galactic rotation','Size of a black hole','Age of the universe'], 0, 'science', 14),
('In quantum mechanics, what does the Pauli exclusion principle state?', ARRAY['Charge is always conserved','No two fermions share identical quantum states','Energy is always quantised','Particles behave as waves'], 1, 'science', 14),
('What phenomenon does the Casimir effect demonstrate?', ARRAY['Superconductivity at low temperature','Magnetic field reversal','Force arising from quantum vacuum fluctuations','Light bending around mass'], 2, 'science', 15),
('What is the approximate value of the fine-structure constant?', ARRAY['1/273','1/42','1/1836','1/137'], 3, 'science', 15),

-- ═══════════════════ HISTORY ═══════════════════
('Who was the first President of the United States?', ARRAY['George Washington','Thomas Jefferson','John Adams','Abraham Lincoln'], 0, 'history', 1),
('In which country were the pyramids of Giza built?', ARRAY['Greece','Egypt','Italy','Peru'], 1, 'history', 1),
('Which ship famously sank in 1912?', ARRAY['Endeavour','Lusitania','Titanic','Britannic'], 2, 'history', 2),
('Who was the Queen of the United Kingdom for most of the 20th century''s latter half?', ARRAY['Mary','Anne','Victoria','Elizabeth II'], 3, 'history', 2),
('Which empire built the Colosseum?', ARRAY['Roman','Ottoman','Persian','Greek'], 0, 'history', 3),
('In which year did humans first land on the Moon?', ARRAY['1967','1969','1971','1973'], 1, 'history', 3),
('Who led the Indian independence movement through non-violence?', ARRAY['Patel','Nehru','Gandhi','Bose'], 2, 'history', 4),
('The First World War began in which year?', ARRAY['1916','1918','1912','1914'], 3, 'history', 4),
('Who was the first Emperor of France?', ARRAY['Napoleon Bonaparte','Charlemagne','Robespierre','Louis XVI'], 0, 'history', 5),
('Which wall divided a German city until 1989?', ARRAY['Hadrian''s Wall','Berlin Wall','Great Wall','Western Wall'], 1, 'history', 5),
('Who was the first person to circumnavigate the globe''s expedition leader?', ARRAY['James Cook','Christopher Columbus','Ferdinand Magellan','Vasco da Gama'], 2, 'history', 6),
('The Renaissance began in which country?', ARRAY['Spain','Germany','France','Italy'], 3, 'history', 6),
('Which civilisation built Machu Picchu?', ARRAY['Inca','Maya','Olmec','Aztec'], 0, 'history', 7),
('Who wrote the Communist Manifesto with Friedrich Engels?', ARRAY['Vladimir Lenin','Karl Marx','Leon Trotsky','Joseph Stalin'], 1, 'history', 7),
('In which year did the French Revolution begin?', ARRAY['1804','1776','1789','1799'], 2, 'history', 8),
('Which pharaoh''s tomb was discovered largely intact in 1922?', ARRAY['Akhenaten','Khufu','Ramesses II','Tutankhamun'], 3, 'history', 8),
('The Ottoman Empire captured Constantinople in which year?', ARRAY['1453','1492','1521','1571'], 0, 'history', 9),
('Who was the longest-reigning monarch of ancient Egypt commonly called the Great?', ARRAY['Seti I','Ramesses II','Cleopatra','Thutmose III'], 1, 'history', 9),
('Which treaty formally ended the First World War?', ARRAY['Treaty of Utrecht','Treaty of Paris','Treaty of Versailles','Treaty of Ghent'], 2, 'history', 10),
('The Black Death reached Europe in which century?', ARRAY['16th','18th','12th','14th'], 3, 'history', 10),
('Who was the first female pharaoh to rule Egypt in her own right for a long reign?', ARRAY['Hatshepsut','Nefertiti','Cleopatra','Sobekneferu'], 0, 'history', 11),
('The Magna Carta was sealed during the reign of which king?', ARRAY['Edward I','King John','Henry II','Richard I'], 1, 'history', 11),
('Which battle in 1066 led to Norman rule in England?', ARRAY['Battle of Agincourt','Battle of Stamford Bridge','Battle of Hastings','Battle of Bosworth'], 2, 'history', 12),
('The Meiji Restoration modernised which country?', ARRAY['China','Korea','Thailand','Japan'], 3, 'history', 12),
('Which empire was ruled by Mansa Musa?', ARRAY['Mali Empire','Songhai Empire','Ghana Empire','Kanem-Bornu'], 0, 'history', 13),
('The Treaty of Tordesillas divided newly discovered lands between which two powers?', ARRAY['Portugal and France','Spain and Portugal','France and England','Netherlands and Spain'], 1, 'history', 13),
('Which dynasty ruled China during the construction of most of the surviving Great Wall?', ARRAY['Tang','Qin','Ming','Han'], 2, 'history', 14),
('The Peace of Westphalia in 1648 ended which conflict?', ARRAY['Hundred Years War','War of the Roses','Seven Years War','Thirty Years War'], 3, 'history', 14),
('Which ancient kingdom was centred on the city of Kerma in Nubia?', ARRAY['Kush','Axum','Saba','Punt'], 0, 'history', 15),
('The Edict of Milan in 313 AD granted tolerance to which religion?', ARRAY['Mithraism','Christianity','Judaism','Zoroastrianism'], 1, 'history', 15),

-- ═══════════════════ LITERATURE ═══════════════════
('Who wrote the play Romeo and Juliet?', ARRAY['Mark Twain','Charles Dickens','William Shakespeare','Jane Austen'], 2, 'literature', 1),
('What is a book of maps called?', ARRAY['Almanac','Dictionary','Thesaurus','Atlas'], 3, 'literature', 1),
('Who wrote the Harry Potter series?', ARRAY['J K Rowling','Roald Dahl','C S Lewis','J R R Tolkien'], 0, 'literature', 2),
('What do you call a story that is not real?', ARRAY['Essay','Fiction','Biography','Report'], 1, 'literature', 2),
('Who wrote The Hobbit?', ARRAY['Philip Pullman','C S Lewis','J R R Tolkien','George Martin'], 2, 'literature', 3),
('A person who writes poems is called what?', ARRAY['Editor','Critic','Novelist','Poet'], 3, 'literature', 3),
('Who wrote Pride and Prejudice?', ARRAY['Jane Austen','Emily Dickinson','Mary Shelley','Charlotte Bronte'], 0, 'literature', 4),
('Which novel features the character Sherlock Holmes as its detective?', ARRAY['The Moonstone','A Study in Scarlet','The Woman in White','Bleak House'], 1, 'literature', 4),
('Who wrote Things Fall Apart?', ARRAY['Ben Okri','Wole Soyinka','Chinua Achebe','Ngugi wa Thiong''o'], 2, 'literature', 5),
('Who created the character Oliver Twist?', ARRAY['George Eliot','Anthony Trollope','Thomas Hardy','Charles Dickens'], 3, 'literature', 5),
('Who wrote the novel Frankenstein?', ARRAY['Mary Shelley','Edgar Allan Poe','Emily Bronte','Bram Stoker'], 0, 'literature', 6),
('In which Shakespeare play does the character Iago appear?', ARRAY['Hamlet','Othello','Macbeth','King Lear'], 1, 'literature', 6),
('Who wrote One Hundred Years of Solitude?', ARRAY['Mario Vargas Llosa','Jorge Luis Borges','Gabriel Garcia Marquez','Pablo Neruda'], 2, 'literature', 7),
('Which epic poem tells of Odysseus''s journey home?', ARRAY['The Aeneid','Beowulf','The Iliad','The Odyssey'], 3, 'literature', 7),
('Who wrote the dystopian novel Brave New World?', ARRAY['Aldous Huxley','H G Wells','Yevgeny Zamyatin','George Orwell'], 0, 'literature', 8),
('Which Nigerian author won the Nobel Prize in Literature in 1986?', ARRAY['Chinua Achebe','Wole Soyinka','Ben Okri','Buchi Emecheta'], 1, 'literature', 8),
('Who wrote Crime and Punishment?', ARRAY['Ivan Turgenev','Leo Tolstoy','Fyodor Dostoevsky','Anton Chekhov'], 2, 'literature', 9),
('In Moby-Dick, what is the name of the ship''s captain?', ARRAY['Starbuck','Queequeg','Ishmael','Ahab'], 3, 'literature', 9),
('Who wrote the poem The Waste Land?', ARRAY['T S Eliot','W B Yeats','Wilfred Owen','Ezra Pound'], 0, 'literature', 10),
('Which author created the fictional county of Yoknapatawpha?', ARRAY['Ernest Hemingway','William Faulkner','John Steinbeck','Flannery O''Connor'], 1, 'literature', 10),
('Who wrote the novel Beloved?', ARRAY['Zora Neale Hurston','Alice Walker','Toni Morrison','Maya Angelou'], 2, 'literature', 11),
('What is the term for a story with a hidden moral or political meaning?', ARRAY['Allusion','Anecdote','Aphorism','Allegory'], 3, 'literature', 11),
('Who wrote In Search of Lost Time?', ARRAY['Marcel Proust','Gustave Flaubert','Andre Gide','Albert Camus'], 0, 'literature', 12),
('What poetic metre consists of five iambic feet per line?', ARRAY['Anapestic trimeter','Iambic pentameter','Dactylic hexameter','Trochaic tetrameter'], 1, 'literature', 12),
('Who wrote the novel Midnight''s Children?', ARRAY['Vikram Seth','V S Naipaul','Salman Rushdie','Arundhati Roy'], 2, 'literature', 13),
('Which literary movement is James Joyce''s Ulysses associated with?', ARRAY['Romanticism','Naturalism','Realism','Modernism'], 3, 'literature', 13),
('Who wrote the play Waiting for Godot?', ARRAY['Samuel Beckett','Eugene Ionesco','Tom Stoppard','Harold Pinter'], 0, 'literature', 14),
('What term describes a narrative voice that cannot be trusted?', ARRAY['Free indirect discourse','Unreliable narrator','Omniscient narrator','Stream of consciousness'], 1, 'literature', 14),
('Who wrote the epic Sanskrit poem the Mahabharata, by tradition?', ARRAY['Kalidasa','Tulsidas','Vyasa','Valmiki'], 2, 'literature', 15),
('What is the literary term for placing two elements side by side for contrast?', ARRAY['Synecdoche','Metonymy','Zeugma','Juxtaposition'], 3, 'literature', 15);
