/**
 * Question Generator Script
 * ─────────────────────────
 * Calls Claude to generate WWTBAM questions for all categories/difficulties
 * and writes a seed SQL file to supabase/seed.sql
 *
 * Usage:
 *   npx tsx scripts/generate-questions.ts
 *
 * Requirements:
 *   ANTHROPIC_API_KEY must be set in .env.local or environment
 */

import Anthropic from "@anthropic-ai/sdk";
import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! });

const CATEGORIES = [
  "random",
  "medicine",
  "law",
  "engineering",
  "finance",
  "science",
  "history",
  "literature",
];

// Difficulty tiers for prompting context
const DIFFICULTY_DESCRIPTIONS: Record<number, string> = {
  1: "very easy, common knowledge any adult would know",
  2: "easy, basic general knowledge",
  3: "easy-medium, well-known facts",
  4: "medium-easy, moderately familiar topics",
  5: "medium, requires some knowledge",
  6: "medium, requires decent knowledge",
  7: "medium-hard, requires good subject knowledge",
  8: "hard, requires solid subject knowledge",
  9: "hard, requires deep knowledge",
  10: "hard, specialized knowledge",
  11: "very hard, expert-level",
  12: "very hard, expert-level specialist",
  13: "extremely hard, professional-level",
  14: "extremely hard, advanced professional",
  15: "near-impossible, only true experts would know",
};

interface GeneratedQuestion {
  text: string;
  options: string[];
  correct_idx: number;
  category: string;
  difficulty: number;
}

async function generateQuestionsForCategory(
  category: string,
  difficulty: number,
  count: number = 5
): Promise<GeneratedQuestion[]> {
  const diffDesc = DIFFICULTY_DESCRIPTIONS[difficulty];
  const categoryContext =
    category === "random"
      ? "general knowledge across any topic (history, science, pop culture, geography, sports, etc.)"
      : `${category} (professional/academic knowledge specific to this field)`;

  const prompt = `Generate ${count} Who Wants to Be a Millionaire quiz questions for the category: ${categoryContext}.

Difficulty level: ${difficulty}/15 — ${diffDesc}.

Rules:
- Each question must have EXACTLY 4 answer options (A, B, C, D)
- Only ONE answer is correct
- Wrong answers should be plausible (not obviously wrong)
- Questions should be factual, not opinion-based
- Do NOT repeat questions

Respond with ONLY a valid JSON array (no markdown, no explanation):
[
  {
    "text": "Question text here?",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "correct_idx": 0
  }
]

correct_idx is 0-based (0=A, 1=B, 2=C, 3=D). Vary which option is correct — don't always use 0.`;

  const response = await anthropic.messages.create({
    model: "claude-haiku-4-5",
    max_tokens: 2000,
    messages: [{ role: "user", content: prompt }],
  });

  const text =
    response.content[0].type === "text" ? response.content[0].text : "";

  // Extract JSON from response
  const jsonMatch = text.match(/\[[\s\S]*\]/);
  if (!jsonMatch) {
    console.error(`Failed to parse JSON for ${category} d${difficulty}:`, text.slice(0, 200));
    return [];
  }

  const parsed = JSON.parse(jsonMatch[0]) as Array<{
    text: string;
    options: string[];
    correct_idx: number;
  }>;

  return parsed.map((q) => ({
    ...q,
    category,
    difficulty,
  }));
}

function escapeSql(str: string): string {
  return str.replace(/'/g, "''");
}

async function main() {
  console.log("🎯 WWTBAM Question Generator\n");

  const allQuestions: GeneratedQuestion[] = [];
  let total = 0;

  for (const category of CATEGORIES) {
    console.log(`\n📚 Generating for category: ${category}`);
    for (let d = 1; d <= 15; d++) {
      process.stdout.write(`  Difficulty ${d}/15... `);
      try {
        const questions = await generateQuestionsForCategory(category, d, 5);
        allQuestions.push(...questions);
        total += questions.length;
        console.log(`✓ ${questions.length} questions`);
        // Small delay to avoid rate limiting
        await new Promise((r) => setTimeout(r, 500));
      } catch (err) {
        console.error(`✗ Error: ${err}`);
      }
    }
  }

  console.log(`\n✅ Generated ${total} questions total`);
  console.log("📝 Writing seed.sql...");

  // Build SQL
  const values = allQuestions
    .map((q) => {
      const optionsArray = q.options
        .map((o) => `'${escapeSql(o)}'`)
        .join(", ");
      return `('${escapeSql(q.text)}', ARRAY[${optionsArray}], ${q.correct_idx}, '${q.category}', ${q.difficulty})`;
    })
    .join(",\n");

  const sql = `-- Auto-generated by scripts/generate-questions.ts
-- ${total} questions across ${CATEGORIES.length} categories × 15 difficulty levels

INSERT INTO questions (text, options, correct_idx, category, difficulty) VALUES
${values};
`;

  const outPath = path.join(process.cwd(), "supabase", "seed.sql");
  fs.writeFileSync(outPath, sql, "utf-8");
  console.log(`\n🎉 Done! Wrote ${total} questions to supabase/seed.sql`);
  console.log(
    "Next step: Run this SQL in your Supabase project → SQL Editor"
  );
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
